export const DISPLAY_ADD = 'DISPLAY_ADD';
export const DISPLAY_REMOVE = 'DISPLAY_REMOVE';
export const DISPLAY_CHANGE = 'DISPLAY_CHANGE';

export const NAVIGATION_LOADING = 'NAVIGATION_LOADING';
export const NAVIGATION_LOADED = 'NAVIGATION_LOADED';

export const FORM_LOADING = 'FORM_LOADING';
export const FORM_LOADED = 'FORM_LOADED';
export const FORM_SUBMITTING = 'FORM_SUBMITTING';
export const FORM_SUBMITTED = 'FORM_SUBMITTED';
